<native:bottom-nav label-visibility="labeled">
    <native:bottom-nav-item
        id="dashboard"
        icon="home"
        :label="__('Dashboard')"
        :url="route('dashboard')"
        :active="Route::is('dashboard')"
    />
    <native:bottom-nav-item
        id="items"
        icon="products"
        :label="__('Items')"
        url="/items"
        :active="Route::is('items:index')"
    />
    <native:bottom-nav-item
        id="add-item"
        icon="add"
        :label="__('Add')"
        url="/items/create"
        :active="Route::is('items:create')"
    />
    <native:bottom-nav-item
        id="settings"
        icon="settings"
        :label="__('Settings')"
        url="/settings"
        :active="Route::is('settings')"
    />
</native:bottom-nav>
